### ISSUE TITLE
Implement Containerized Application for Receiving Data from the Metadata Services

### ISSUE THREAD

**Issue by zliang-akamai** [linode/k8s-node-decorator#5]
We will need a containerized application actively poll metadata from Linode Metadata Service

**Comment by zliang-akamai** [comment]
This is currently blocked by the go metadata client

**Comment by schinmai-akamai** [comment]
@zliang-akamai are you good to work on this? or I can pick it up, now that go-metadata is out

**Comment by zliang-akamai** [comment]
@schinmai-akamai Yea, I am fine. I got it mostly, will post my PR soon
